### ISSUE TITLE
More wrong references to maximum-concurrent-tasks property

### ISSUE THREAD

**Issue by sabbyanandan** [spring-io/dataflow.spring.io#106]
As a user, while reviewing the SFTP -> JDBC sample, I notice the wrong references to `maximum-concurrent-tasks` property in the following YAML and in other places. Review [from this point](https://dataflow.spring.io/docs/recipes/file-ingest/sftp-to-jdbc/#lower-the-maximum-concurrent-task-executions) onwards.

```
apiVersion: v1
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    maximum-concurrent-tasks: 3
                    limits:
                      memory: 1024Mi
                      cpu: 500m
```
