### ISSUE TITLE
The `Accessing the Host File System` guide is incomplete

### ISSUE THREAD

**Issue by tzolov** [spring-io/dataflow.spring.io#128]
In the [Accessing the Host File System](https://dataflow.spring.io/docs/installation/local/docker-customize/#accessing-the-host-file-system) guid the source host folders must be mount to bot the `dataflow-server` and the `skipper-server` service definitions! 

The same host and container folder paths used in dataflow-server must be mounted to the skipper-server as well:

```
skipper-server:
    image: springcloud/spring-cloud-skipper-server:${SKIPPER_VERSION:?SKIPPER_VERSION is not set!}
    container_name: skipper
    ports:
      - "7577:7577"
      - "9000-9010:9000-9010"
      - "20000-20105:20000-20105"
    environment:
      - SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_LOCAL_ACCOUNTS_DEFAULT_PORTRANGE_LOW=20000
      - SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_LOCAL_ACCOUNTS_DEFAULT_PORTRANGE_HIGH=20100
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dataflow
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpw
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
    volumes:
      - /tmp/apps:/root/apps
    entrypoint: "./wait-for-it.sh mysql:3306 -- java -Djava.security.egd=file:/dev/./urandom -jar /spring-cloud-skipper-server.jar"
 volumes:
   - /thing1/thing2/apps:/root/apps
```
