### ISSUE TITLE
Service Account Optimum Role

### ISSUE THREAD

**Issue by umutcann** [spring-io/dataflow.spring.io#270]
Hi,

I followed the document to deploy multiple namespaces below.

As you mentioned in document, service account cluster admin right is not appropriate for production. 

What should be the optimum permission for service account?

**Setting the cluster role to cluster-admin for the scdf-sa user is not something that is recommended for production, but in this case it is meant for demo purposes.**

https://github.com/spring-io/dataflow.spring.io/blob/master/content/documentation/pages/6-recipes/5-multi-platform-deployment/2-multi-platform-task.md

Thanks in advance.

**Comment by sabbyanandan** [comment]
Perhaps @chrisjs might have a perspective here. cc:/ @cppwfs

**Comment by chrisjs** [comment]
the "optimum permissions" are those that are best suited for your environment and policies. i would recommend reading the kubernetes RBAC documentation.

heres one way to do it that works fine, you should review and apply to your environment as appropriate. its assumed scdf is deployed to the `default` namespace and assumes your other platform will be configured to deploy to a namespace called `test-ns`. other attributes in the configuration are based on the stock, unmodified distribution yamls that come with scdf

* create ns if needed:

```
kubectl create ns test-ns
```

* kubectl apply the following into `default` ns:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: scdf-cr
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "replicationcontrollers", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: scdf-binding
subjects:
- kind: ServiceAccount
  name: scdf-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: scdf-cr
  apiGroup: rbac.authorization.k8s.io
```

kubectl apply the following to the `test-ns` namespace you created and any additional ones you create (updating the `namespace` attributes as appropriate):

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: scdf-binding
  namespace: test-ns
subjects:
- kind: ServiceAccount
  name: scdf-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: scdf-cr
  apiGroup: rbac.authorization.k8s.io
```

launch a task to the platform thats configured for the namespace you created the RoleBinding for and it would be successful, ie:

```
$ kubectl get all --namespace test-ns
NAME               READY   STATUS      RESTARTS   AGE
pod/d-lxyweqnzwx   0/1     Completed   0          11s
```
