### ISSUE TITLE
The Wavefront SCDF configuration is incorrect

### ISSUE THREAD

**Issue by tzolov** [spring-io/dataflow.spring.io#282]
The `server-configuration.yml` under the https://dataflow.spring.io/docs/installation/kubernetes/kubectl/#wavefront documentation is incorrect.  
* Following section has to be removed as it is redundant and incorrectly indented:
```yaml 
web:
          server:
            request:
              autotime:
                enabled: true
            metric-name: spring.cloud.dataflow.http.server.requests
```

* the `export:` and below are incorrectly indented regarding the parent `metrics:` element. 

The snippet needs to be changed to something like:

```yaml
data:
  application.yaml: |-
    management:
      metrics:
        export:
          wavefront:
            enabled: true
            api-token: ${wavefront-api-token}
            uri: https://yourwfuri.wavefront.com
            source: yoursourcename
```

Change should be backported to 2.6.x
