### ISSUE TITLE
Fix Wavefront configuration in 2.7/2.8 docs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-io/dataflow.spring.io#329]
The current docs point to the following, but they aren't required in v2.7 and onwards.

```
spring:
  cloud:
    dataflow:
      applicationProperties:
        stream:
          management:
            metrics:
              export:
                wavefront:
                  enabled: true
                  api-token: <YOUR API-KEY>
                  uri: <YOUR WAVEFRONT-URI>
                  source: demo-scdf-source
```
